### ISSUE TITLE
add range filter on numbers

### ISSUE THREAD

**Issue by leeeqian** [leeeqian/gmap_filter#2]

**Comment by xiehaom7** [comment]
Hi, I implemented a range filter in my branch https://github.com/xiehaom7/gmap_filter.git. 

Also, I extracted the filter operations out of the GmapFilter, and wrapped them into a separated class. So, when adding new filter types, just define new a class as well as the necessary methods (see filters_def.js).

**Comment by leeeqian** [comment]
The change is merged into master branch.

I also made range filter figure out the min/max automatically; and made range filter vertically.
Thanks a lot!
